language: java
jdk:
  - oraclejdk7
before_script: cd src  
script: javac -g ArraySums.java  
after_success: java -cp . ArraySums > output.txt
after_script: 
  - cd ..
  - git add .
  - git status
  - git commit -m "add output file"
  - git remote set-url origin https://viperguynaz:giggles*01@github.com/BASISPhoenix/11-05-ArraySums.git
  - git push -u origin master

