language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - git config --global user.email "viperguynaz@gmail.com"
  - git config --global user.name "viperguynaz"
  - git remote rm origin
  - git remote add origin https://d73adfc8af68c19aadab818670d3999ed4ce75cd@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout master -qf
  - cd src  
script: javac -g ArraySums.java  
after_success: java -cp . ArraySums > output.txt
after_script: 
  - cd ..
  - git add -f ./output.txt
  - git commit -m "add output text file"
  - git push -fq  origin master > /dev/null
 
