language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - cd src  
script: javac -g ArraySums.java  
after_success: 
  - java -cp . ArraySums > solution.txt
  - diff output.txt solution.txt > diff.txt
  - dir
after_script: 
   - git init
   - git config user.email "viperguynaz@gmail.com"
   - git config user.name "viperguynaz"
   - git add .
   - git commit -m "Deploy to Github Pages"
   - git push -fq "https://d73adfc8af68c19aadab818670d3999ed4ce75cd@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages > /dev/null 2>&1
