language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - git checkout gh-pages
  - dir 
  - cd src  
script: javac -g ArraySums.java  
after_success: 
  - java -cp . ArraySums > solution.txt
  - diff output.txt solution.txt > diff.txt
  - dir
after_script: 
   - mkdir pages
   - cd pages
   - git init
   - git config user.email "viperguynaz@gmail.com"
   - git config user.name "viperguynaz"
   - git checkout "https://d73adfc8af68c19aadab818670d3999ed4ce75cd@github.com/${TRAVIS_REPO_SLUG}.git" master:gh-pages
   - cp ../output.txt output${TRAVIS_PULL_REQUEST}.txt
   - cp ../soultion.txt solution${TRAVIS_PULL_REQUEST}.txt
   - cp ../diff.txt diff${TRAVIS_PULL_REQUEST}.txt
   - dir
   - git add . 
   - git commit -m "Deploy to Github Pages"
