language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - git config --global user.email "viperguynaz@gmail.com"
  - git config --global user.name "viperguynaz"
  - git remote rm origin
  - git remote add origin https://d73adfc8af68c19aadab818670d3999ed4ce75cd@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout master -qf
  - cd src  
script: javac -g ArraySums.java  
after_success: 
  - java -cp . ArraySums > solution.txt
  - diff output.txt solution.txt > diff.txt
after_script: 
  - cd ..
  - echo "what....?"
  - git add -f .
  - git commit -m "add output text file"
  - if [ "${TRAVIS_PULL_REQUEST}" ] then
  -    git push -fq origin +refs/pull/${TRAVIS_PULL_REQUEST}/merge:master > /dev/null
  -  else
  -    git push -fq origin master > /dev/null 
  -  fi
 
