language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - cd src  
script: javac -g ArraySums.java  
after_success: 
  - java -cp . ArraySums > solution.txt
  - diff output.txt solution.txt > diff.txt
  - dir
after_script: 
  - cd ..
  - git add .
  - git commit -m "add output text file"
  - git push -fq origin master > /dev/null
