language: java
jdk:
  - oraclejdk7
env:
  global:
    secure: "d73adfc8af68c19aadab818670d3999ed4ce75cd"
    
before_script: 
  - mkdir $HOME/gh-pages
  - cd src

script: javac -g ArraySums.java  
after_success: 
  - java -cp . ArraySums > solution.txt
  - diff output.txt solution.txt > diff.txt
  - cp output.txt $HOME/gh-pages/output-${TRAVIS_PULL_REQUEST}.txt
  - cp solution.txt $HOME/gh-pages/solution-${TRAVIS_PULL_REQUEST}.txt
  - cp diff.txt $HOME/gh-pages/diff-${TRAVIS_PULL_REQUEST}.txt
  - cd $HOME/gh-pages
  - dir
  
after_script: 
  - cd $HOME
  - git clone --depth=50 --branch=gh-pages git://github.com/${TRAVIS_REPO_SLUG}.git gh-pages > /dev/null
  - cd gh-pages
  - git checkout -fq gh-pages
  - dir
  
